### ISSUE TITLE
Hla input stream stuck on lowest quality

### ISSUE THREAD

**Issue by pranksta02** [m1k1o/hls-restream#7]
Hi there,

This tool is working great except I am trying to use an input stream which is hls and only when get it restreamed at the lowest quality (there are 4 or 5 streams within the hls, last one being the 1080 one. Is it something I am doing wrong or is there a way to force the restream of the 1080 stream?

**Comment by m1k1o** [comment]
Hi, that means your stream is already transcoded and you don't need to retranscode it, just doing passthrough, right?

**Comment by pranksta02** [comment]
Yes just set as pass through but only getting the SD stream on the output stream

**Comment by m1k1o** [comment]
Here is selected only the first video+audio. You could modify that to whatever value you need.
https://github.com/m1k1o/hls-restream/blob/9cdca88f5bc4d74c38383ced0afcc1754e7e4f40/profiles/passthrough.sh#L4

But since you don't need transcoding it would be more appropriate for you to use hls proxy. That is part of the [go-transcode](https://github.com/m1k1o/go-transcode) project.

**Comment by pranksta02** [comment]
Thank you very much, I'll check it out!

**Comment by pranksta02** [comment]
Thank you, updating the map command allowed me to select the 1080 stream. The stream stutters a fair bit however, so am going to try your other project.
