### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by BigO-Moha** [m1k1o/hls-restream#8]
i'm getting build error.

this is my output:- 

Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'

**Comment by m1k1o** [comment]
We do not build anything here, because its all just bash scripts.

Dockerfile should just install dependencies `ffmpeg nginx supervisor`, create non-root user and copy files.

So maybe latest ubuntu image has some errors? Or you have some old ubuntu? Try to execute `docker pull ubuntu` before building.

**Comment by BigO-Moha** [comment]
fixed,

can i change the default 80 port to another port  which i'm currently using for other thing. why i cannot access m3u file via public digital ocean ip ?

**Comment by BigO-Moha** [comment]
thanks
