### ISSUE TITLE
question ???

### ISSUE THREAD

**Issue by BigO-Moha** [m1k1o/hls-restream#9]
how much traffic or users can handle digital ocean 12$ / moth can you estimate please ?

**Comment by m1k1o** [comment]
That one?

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/7534274/199829855-c35c6814-af2b-4c4e-b2e4-f9af62878e85.png">

Speaking about 2000GB data transfer, and 24/7 nonstop streaming it could be 6000kbps stream with 1 user. Or 6 users with 1000kbps stream

If you don't plan on 24/7 usage then you need to count that accordingly and maybe setup a test VM to see. Because CPU usage depends on stream sources you use and traffic on stream profiles you choose.

**Comment by BigO-Moha** [comment]
ok , i think thats not enough for me .
